### PR TITLE
Added unit tests

### PR DESCRIPTION
**Pull request by youngrafi**
Mainly was looking for a simple project to practice unit testing in Javascript. Figured I'd upload the added tests. They're a direct reflection of the readme examples.

### CODE REVIEW

**Comment by RReverser** [comment]
Thanks!

**Comment by RReverser** [comment]
@youngrafi Could you please also add it as test command to `package.json` so `npm test` would work?

**Comment by youngrafi** [comment]
I originally added a Karma config so you could run the tests using Karma with Jasmine. I don't know much about unit testing for Javascript, and saw that this was what was being used in AngularJS so gave it a try (Although they also setup the package.js to run the tests). Anyway, I saw you set tests to run with mocha, and seems to be running well, so I guess nothing's needed anymore.

**Comment by RReverser** [comment]
@youngrafi Yeah, I already converted to Mocha, added more tests for new customizations + configured Travis. Thanks for your contribution!

**Pull request merged**
